# Generated by Django 5.0 on 2026-01-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
